// examples/vite-solid/src/index.tsx
/** @jsxImportSource solid-js */
/** Applies the root theme, then mounts the playground with Solid's renderer. @module */
import { render } from 'solid-js/web'
import 'zyzz/reset.css'
import { App } from './App.js'
import { appearance } from './appearance.js'

const root = document.getElementById('root')
if (!root) throw new Error('Missing playground root.')

appearance.restore()
render(() => <App />, root)

// examples/api-react/src/main.tsx
/** Applies the root theme, then mounts the playground with ordinary React props. @module */
import { createRoot } from 'react-dom/client'
import 'zyzz/reset.css'
import { App } from './App.js'
import { appearance } from './appearance.js'

const root = document.getElementById('root')
if (!root) throw new Error('Missing playground root.')

appearance.restore()
createRoot(root).render(<App />)
